# Permalinks
permalink:        pretty

# Settings
markdown:         kramdown
destination:      ./_gh_pages
exclude:          ["README.md"]
paginate:         10
encoding:         UTF-8
future:           false
name:             Built By Moroccan Devs
url:              http://builtbymoroccandevs.com 
description:      "Awesome stuff built by Moroccan developers."
